admin:
- 5132684972 
bot:
 api_id: 20805330 
 api_hash: abd8a39c51b8872a9d0e1388f17e9cae 
 bot_token: 6944924897:AAF5BJayQiYhv23y471dY3vvMBZCrf043to
 bot:
 proxy: 127.0.0.1:5080
 bot:
 scripttext: "⏳联通性测试进行中..."
 bot:
 analyzetext: "⏳节点拓扑测试进行中..."
 bot:
 speedtext: "⏳速度测试进行中..."
 bot:
 bar: "="
 bleft: "["
 bright: "]"
 bspace: "  "
 bot:
 command: 
 - "command1"
 - "command2"
 - "command3"
 clash:
 branch: meta 
 clash:
 cache-time: 60
 clash:
 core: 1
 image:
 title: '机场订阅节点测速' 
 color:
  speed: 
   - { label: 0, name: '云水', value: '#B4C3D0', alpha: 255 }
   - { label: 1, name: '晴山', value: '#91AEC4', alpha: 255 }
   - { label: 5, name: '秋波', value: '#8BB8CB', alpha: 255 }
   - { label: 10, name: '天韵', value: '#5796B3', alpha: 255 }
   - { label: 20, name: '鸢尾', value: '#1988AE', alpha: 255 }
   - { label: 60, name: '甸子', value: '#238BBC', alpha: 255 }
   - { label: 100, name: '景泰', value: '#2A73AC', alpha: 255 }
  delay: ms
   - { label: 1, name: '云水', value: '#B4C3D0', alpha: 255 }
   - { label: 100, name: '晴山', value: '#91AEC4', alpha: 255 }
   - { label: 200, name: '秋波', value: '#8BB8CB', alpha: 255 }
   - { label: 300, name: '天韵', value: '#5796B3', alpha: 255 }
   - { label: 500, name: '鸢尾', value: '#1988AE', alpha: 255 }
   - { label: 1000, name: '甸子', value: '#238BBC', alpha: 255 }
   - { label: 2000, name: '景泰', value: '#2A73AC', alpha: 255 }
   - { label: 99999, name: '景泰', value: '#8d8b8e', alpha: 255 }  
  "yes": '#bee47e' 
  "yesalpha": 255 
  "no": '#ee6b73' 
  "noalpha": 255 
  na: '#8d8b8e' 
  naalpha: 255  
  wait: '#dcc7e1' 
  waitalpha: 255  
  iprisk: 
   low: '#ffffff'
   lowalpha: 255
   medium: '#ffffff'
   mediumalpha: 255
   high: '#ffffff'
   highalpha: 255
   veryhigh: '#ffffff'
   veryhighalpha: 255
  warn: '#fcc43c' 
  warnalpha: 255
  image:
 watermark:
  enable: true 
  text: '机场节点测速' 
  color: '#000000' 
  alpha: 16 
  font_size: 64 
  angle: -16.0 
  row_spacing: 0 
  start_y: 0
  image:
 background:
  backgrounds: '#ffffff' 
  ins: '#ffffff' 
  outs: '#ffffff' 
  speedtest: '#ffffff' 
  speedtitle: '#EAEAEA' 
  testtitle: '#EAEAEA' 
  topotitle: '#EAEAEA'
  
  buildtoken: 1234567890abcdefgh
  userconfig: 
  rule: 
    "qz":
      enable: true 
      slaveid: local  
      script: ["Netflix", "Youtube", "Disney+", "维基百科"]
      sort: "HTTP升序"
      geoip-api: ip.sb
      pingurl: https://www.gstatic.com/generate_204
      netflixurl: "https://www.netflix.com/title/80113701"
      speednodes: 45
      speedthread: 1
      speedconfig:
 interval: 15
 entrance: ip
 entrance: cluster
 
      
      
  
  
  
  
  
  
 
 
 
 
 
 
 
 
 
     
